### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by AlexDarchuk** [AlexDarchuk/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Olena-Kunovska** [comment]
EXPERIENCE

The Nobel Prize in Physics 1921

Facts from Einstein's biography

1. Einstein was an excellent high school student. Moreover, he was so good at mathematics that he studied mathematical analysis at the age of 12, three years earlier than usual. At the age of 15, Einstein wrote an advanced essay, which became the basis for his further work in the theory of relativity.
2. Albert Einstein loved sports. In addition to swimming, which he called a sport that requires the least energy.
3. The myth that Einstein studied horribly in school was born out of differences in labeling systems between German and Swiss schools. When Einstein changed the German school to a school in the canton of Aargau in Switzerland, the classification system - from 1 to 6 (as from 5 to 1 in our country) - was reversed. A score of 6, which meant a lower score, became higher, and a unit, which meant a higher score, became a lower score ( interesting facts about Switzerland ).
4. Einstein is the author of about 300 works on physics, as well as the author of more than 150 books in other sciences.
5. In addition to the theory of relativity, Einstein's account has several other inventions. Among them, for example, a gyrocompass and an improved model of a hearing aid.
6. After entering the Polytechnic, the student Einstein often missed lectures, instead reading in a cafe magazines with the latest scientific theories.
7. Einstein agreed to have his brain examined after his death.

8. Albert Einstein spoke very harshly about science fiction and did not recommend reading it, as he was convinced that it distorts science and gives readers misconceptions about it.
9. Einstein was an avid non-drinker and welcomed the introduction of dry law in the United States, but could not quit smoking.
10. Few people know that Einstein proposed the design of a refrigerator that has no moving parts, does not require electricity and uses the energy of low-power heating devices.
11. Einstein was passionate about sailing all his life. He often liked to go on a yacht in complete solitude.
12. Einstein adored women, and women, in turn, adored Einstein. Romantic letters, painful breaks, marriage to a cousin, countless betrayals… It is very easy to get confused in the love adventures of a genius.
13. The political views of the famous scientist were moderately leftist, which was the reason for the FBI's attention to him. From the day Einstein moved to the United States, the service secretly monitored him, reviewed his letters, and recorded telephone conversations. By the time of his death, his case was 1,427 pages long. The version that Einstein was a Soviet spy was seriously considered, and for some time there was even a threat of expulsion of the scientist from the country.
14. Einstein loved good movies and especially Charlie Chaplin's films. Once, after watching the film "Gold Rush", the genius of science sent a letter to the young director, in which he praised the picture, said that it was understood by all, and assured Chaplin that he would definitely become a great man. And after a while I received a witty answer: "You cause me even more admiration! After all, you have created a theory that no one understands, and, despite this, you have become great! ”
15. The funniest photo of Einstein - with his tongue out - was taken by photojournalist Arthur Sass during the celebration of the scientist's 72nd birthday. Sass was so tired of the birthday boy with his camera that he rewarded him with a grimace. When the film was developed, Einstein liked the picture very much.
16. Einstein failed the college entrance exams. Before getting to Aargau, where the myth of poor education came from, he tried to enter the Federal Polytechnic School in Switzerland. And although he passed the exams in mathematics and physics excellently, in some non-scientific subjects, especially in French, he scored few points.
17. Albert Einstein was a staunch pacifist.
18. After graduating, Einstein was hired to work as an expert in the patent office. Due to the fact that the assessment of technical characteristics of a young specialist often took only about 10 minutes, he did a lot of work to develop their theories.
19. In 1952, he was offered the presidency of Israel, but he respectfully withdrew from the answer, citing his inexperience in this matter ( interesting facts about Israel ).
20. One of the Israeli banknotes depicts a portrait of Albert Einstein.
21. Einstein was a lifelong member of the Montreal Pipe Smokers Club.
22. Einstein's parents were against his first marriage.
23. It is said that Einstein was not very neat and once said: "When I was young, I learned that the thumb always ends in a hole in a sock. So I stopped wearing socks. "
24. Einstein also invented a blouse that had two sets of buttons sewn parallel to each other. One set of buttons would suit a thin person, and another would suit a larger person.
25. Einstein began playing the violin at the age of six.
26. In the 1920s, a campaign against Einstein began in Berlin. The speeches and attacks of anti-Semitic scholars were based on a critique of the theory of relativity. Authorities responded in silence to the persecution of the scientist. After Hitler came to power in 1933, Einstein was forced to flee to the United States ( interesting facts about the United States ).
27. Einstein could have been a brilliant scientist, but he was far from perfect. In fact, he made at least seven errors in various proofs E = mc ^ 2.
28. Einstein's second wife was his cousin.
29. Einstein asked people for a dollar for his autograph. He sent all the money collected in this way to charity.
30. Albert Einstein is one of the founders of the Hebrew University of Jerusalem.
31. Einstein and composer Hans Eisler once found themselves together in the same company. The hosts knew that Einstein played the violin well, and asked him to play with Eisler. The composer agreed, Einstein tuned his violin, but nothing came of it. No matter how many times Eisler started playing the introduction, Einstein could not get in time. Eisler got up from the piano and said: "I do not understand why the whole world considers a great man who can not count to three!".
32. On the eve of Einstein's death, he was offered surgery, but he refused, saying that "artificial life extension does not make sense."
33. Einstein's last words remained a mystery. When he was dying in the hospital, an American nurse was sitting next to him, and he said his last words in German, and she didn't understand him.
>
