### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by AlexDarchuk** [AlexDarchuk/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Olena-Kunovska** [comment]
LANGUAGES

ENGLISH  GERMAN

SKILLS

The most important skills of albert einstein were imagination and curiosity . because once a girl asked him what special talent do you have he said i don’t have any special talent i am just curios . also because of his imagination power he was able to discover special relativity , general relativity.

DISCOVERY

- General theory of relativity
- Special theory of relativity
- Brownian motion
- Photoelectric effect
- EPR paradox
- Equivalence of mass and energy
- Field equations
- Bose - Einstein statistics Bose - Einstein
- condensation
